### ISSUE TITLE
kie-wb-common depends on a JSON license component

### ISSUE THREAD

**Issue by phkrief** [eclipse-researchlabs/kie-wb-common#1]
Dear @teohaik ,

I hope you are doing fine.
I identified some issues regarding the forks of kie-wb-common and kie-wb-distributions.
One of them is well known: kie-wb-common has a dependency with the component: maven/mavencentral/org.json/json/20090211 which is under the JSON license. 

Unfortunately, this license is NOT an open-source silence (as I mentioned in Madrid).

The repository smartclide-security has the same dependency and @deanone is working on it to replace this library with a friendly library. 

Do you have have such freedom as well with the code: can you replace this library by a business-friendly library or can you ask the owner of the kie-wb-common to fix it?

Thx a lot

**Comment by phkrief** [comment]
Dear @schlotze and @deanone 

Do you work on this issue? I didn't receive any answer from @teohaik. Thx

**Comment by deanone** [comment]
@phkrief, I believe @teohaik is no longer working on SmartCLIDE. This repo is a fork of this project:

https://github.com/kiegroup/kie-wb-common

From the commit history, I saw that Nikos Nikolaidis made changes to only the docker-image.yml file. I think we should consider deleting this. @schlotze , WDYT?

**Comment by schlotze** [comment]
if the only change is the docker-image.yml, I think that we should delete the repository and find another solution for building this dependenvy

**Comment by deanone** [comment]
Ok, then @phkrief @eclipsewebmaster you can proceed with deleting the repo.

**Comment by nikosnikolaidis** [comment]
Dear @deanone @schlotze @phkrief 

I am working on this repo, but I haven't noticed this issue before. Sorry about that!
All my changes are in the branch "SmartCLIDE-addons" and are all the changes that we make in jbpm to add the functionality of OpenSmartCLIDE.
So we can't delete it.
I am going to work on this issue!

**Comment by deanone** [comment]
@nikosnikolaidis thank you for your quick response!

Ok, then we leave it as is. Please keep us posted if you need anything.

**Comment by nikosnikolaidis** [comment]
The dependency with the JSON license seams to be originated from this [repo](https://github.com/kiegroup/droolsjbpm-integration) of kiegroup, and in particular in [this](https://github.com/kiegroup/droolsjbpm-integration/tree/7.61.0.Final/jbpm-simulation) module.
This repo has an Apache-2.0 license. @phkrief if they have to change it as well (in order to comply with their license), maybe we should contact them!

**Comment by deanone** [comment]
@nikosnikolaidis I do not believe that they will make any change in their licensing scheme because it is causing trouble with an adopter of their technology. Maybe, we should the other way around and consider using some other dependency that does not have this licensing issue. What are you using this module for? Are there any other components/frameworks that you can use that do not have this license issue?

**Comment by nikosnikolaidis** [comment]
@deanone No I don't mean that they will change their licensing. Only if they violate their license basically like us, without knowing about the JSON license, and they have to change it.

I can find another dependency but in order to change it is going to be a bit tricky.
My idea so far is to get this module inside our repo, make the appropriate changes, and when the mvn goes through the install face, store it with a different name, and change the parent module accordingly.

**Comment by deanone** [comment]
@nikosnikolaidis yes I get it. However, this does not solves the license issue. I think that the only solution on this will be to use another similar module with a compatible license.

**Comment by nikosnikolaidis** [comment]
@deanone Yes I agree. But if this library violates their license as well, they will have to change it and use another library with a compatible license. And we will only have to just sync our fork.
But I dont know if the JSON license is compatible with the Apache-2.0. Maybe @phkrief can help with this.

**Comment by deanone** [comment]
@nikosnikolaidis I do not understand. Why the contributors of this [repo](https://github.com/kiegroup/droolsjbpm-integration) should change their license should choose their license? Maybe I missed something here.

My understanding is that you are using a module of the repo I mentioned above, and this module uses the JSON license. The JSON license is incompatible with EPL. Hence, AFAIU, you need to use another module/library with a compatible license. This has nothing to do with the maintainers of the kiegroup repo.

**Comment by nikosnikolaidis** [comment]
@deanone this [repo](https://github.com/kiegroup/droolsjbpm-integration) is also part of kiegroup, and its modules are being used in kie-wb-common. Its not that I chose to add a module of that repo, it was in the original code. 
So if the JSON license is incompatible with Apache-2.0 (that kiegroup uses), the contributors of kiegroup will have to change the org.json library in that module, and as a result the kie-wb-common will not depend in a JSON license.

**Comment by deanone** [comment]
@nikosnikolaidis kie-wb-common is a set of utilities for programmatically configuring jBPM workflows?

**Comment by nikosnikolaidis** [comment]
@deanone in a nutshell, the jBPM that we use comes from the [kie-wb-distributions](https://github.com/kiegroup/kie-wb-distributions) which is more or less a placeholder for a lot of modules that create the jBPM. One of them is kie-wb-common, which contains the screens and functionality we have to change for OpenSmartCLIDE. 
And kie-wb-common itself uses also a lot of different modules of kiegroup. And one of them is the [jbpm-simulation](https://github.com/kiegroup/droolsjbpm-integration/tree/7.61.0.Final/jbpm-simulation) which uses the org.json library (that has the JSON license).

**Comment by deanone** [comment]
> @deanone in a nutshell, the jBPM that we use comes from the [kie-wb-distributions](https://github.com/kiegroup/kie-wb-distributions) which is more or less a placeholder for a lot of modules that create the jBPM. One of them is kie-wb-common, which contains the screens and functionality we have to change for OpenSmartCLIDE. And kie-wb-common itself uses also a lot of different modules of kiegroup. And one of them is the [jbpm-simulation](https://github.com/kiegroup/droolsjbpm-integration/tree/7.61.0.Final/jbpm-simulation) which uses the org.json library (that has the JSON license).

@nikosnikolaidis apologies for the late response. Right, so yes this is the understanding I had. So, given this structure of components (some of them we are using), how to do we expect from the jbpm-simulation contributors to change the org.json library? I mean, how do we convince them to do such a change?

**Comment by nikosnikolaidis** [comment]
@deanone We can convince them by telling them that the org.json library has a JSON license that is incompatible with  Apache-2.0 (that they use).
I made a fork of this repo and I am working on changing this library.
But in the meantime I found out the the org.json library changed its license in the [last release](https://github.com/stleary/JSON-java/releases/tag/20220924), so maybe we can just open an issue for them to update the version of the library.

**Comment by deanone** [comment]
@nikosnikolaidis I have checked the change you mentioned about license of the org.json library. It turns out that this change does not solve the issue. If you look [here](https://github.com/stleary/JSON-java/blob/master/LICENSE), the current version of the LICENSE file includes only the statement "Public Domain.". However, as described [here](https://opensource.org/node/878), this does not mean the now the software is open source. In essence, public-domain != open-source. So, the problem remains. @phkrief any thoughts?

**Comment by nikosnikolaidis** [comment]
Dear all,
I was able to remove the org.json library from the jbpm-simulation module.
So I can add this module in our repo, make the appropriate changes, link the other modules that use it to the new one. And in the build state we can install this package locally and then use it in kie-wb-common.

**Comment by deanone** [comment]
@nikosnikolaidis thanks for the update. Alright, so since the org.json library has been removed, we can consider the issue resolved (I am closing it).
